version: '3.8'

services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: PDC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  frontend:
    build: ./front-end
    ports:
      - "3000:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    depends_on:
      - backend

  backend:
    build: ./back-end
    ports:
      - "4000:4000"
    volumes:
      - ./back-end:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/PDC
    working_dir: /app



volumes:
  postgres_data:

